Tag to label
illumio/terraform-provider-illumio-cloudsecure pull request #116
Opened 2024-11-27 21:24 UTC by shireesh-illumio

This pull request introduces `Tag to label` resource.

2025-01-09 20:55 UTC, rlenglet requested changes

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
Is this mutable?
If not, declare it so:
```suggestion
				"key": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description:   "Key of the created CloudSecure labels.",
						Required:      true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					attributeWithMode: attributeWithMode{
						Mode: ImmutableAttributeMode,
					},
				},
```

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
Is this mutable?
If not, declare it so:
```suggestion
				"name": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description:   "Display name of the created CloudSecure labels.",
						Required:      true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					attributeWithMode: attributeWithMode{
						Mode: ImmutableAttributeMode,
					},
				},
```

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +					Description: "List of AWS account tags to map to the CloudSecure label.",
```suggestion
					Description: "List of AWS account tags to map to CloudSecure labels with the specified key. The values of the created labels correspond to the values of the tags.",
```

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				"icon": resource_schema.ObjectAttribute{
Same as above: is this immutable?

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				"cloud_tags": resource_schema.ListAttribute{
Same as above: is this immutable?

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +					Description: "List of AWS account tags to map to the CloudSecure label.",
Since we can't specify any validators on the object fields, esp. a `OneOf` on the `cloud` field, you have to document the restrictions on `cloud` in the description here, something like `The cloud field for each tag must be \"aws\" or \"azure\"`.

2025-01-09 20:55 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +			Attributes: map[string]resource_schema.Attribute{
Reorder the attributes to be in alphabetic order after `IDFieldName`.

2025-01-09 21:12 UTC, rlenglet requested changes

2025-01-09 22:13 UTC, gshireesh commented on api/schema/schema.go
> +		awsTagToLabelResource,
modified the name to tag_to_label. so it works for all clouds.

2025-01-09 22:14 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +				"icon": resource_schema.ObjectAttribute{
no it can be updated

2025-01-09 22:14 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +				"cloud_tags": resource_schema.ListAttribute{
no all the fields are updatable.

2025-01-09 22:15 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +					Description: "List of AWS account tags to map to the CloudSecure label.",
updated the description to reflect the cloud values

2025-01-09 22:17 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +			Attributes: map[string]resource_schema.Attribute{
added. i tried to create test case to test but since its map of strings order is not preserved.

2025-01-09 22:17 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +					},
modified the resource name to be tag_to_label. applies for all clouds.

2025-01-10 19:42 UTC, rlenglet requested changes

2025-01-10 19:42 UTC, rlenglet commented on api/schema/tag_to_label_resource.go
> +			MarkdownDescription: "Maps AWS account tags to CloudSecure labels.",
```suggestion
			MarkdownDescription: "Maps cloud resource tags to CloudSecure labels.",
```

2025-01-10 19:42 UTC, rlenglet commented on api/schema/tag_to_label_resource.go
> +				"cloud_tags": resource_schema.ListAttribute{
There is no ambiguity that these are "cloud" tags. In the `aws` provider's resources, this attribute is simply named `tags`, e.g., [in the `aws_instance` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#tags-3). Use the same name for consistency.
```suggestion
				"tags": resource_schema.ListAttribute{
```

2025-01-10 19:42 UTC, rlenglet commented on api/schema/tag_to_label_resource.go
> +					MarkdownDescription: "List of tags to map to CloudSecure labels with the specified key. The values of the created labels correspond to the values of the tags. The cloud field for each tag must b
Don't refer to OCI, until we properly support onboarding OCI accounts in this Terraform provider.

2025-01-10 19:42 UTC, rlenglet commented on api/schema/tag_to_label_resource.go
> +				},
1. To be consistent with how we're modeling Deployments (#128) and our other resources,
    1. Remove the `cloud` field altogether.
    1. Split this into two fields: `aws_tags`, `azure_tags`.
2. Make these Sets instead of Lists.
```suggestion
				"aws_tag_keys": resource_schema.SetAttribute{
					Description: "Sets of keys of AWS resource tags to map to CloudSecure labels with the same keys. The values of the created labels correspond to the values of the tags.",
					Required:    true,
					ElementType: types.StringType,
				},
				"azure_tag_keys": resource_schema.SetAttribute{
					Description: "Set of keys of Azure resource tags to map to CloudSecure labels with the same keys. The values of the created labels correspond to the values of the tags.",
					Required:    true,
					ElementType: types.StringType,
				},
```

2025-01-10 19:42 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
You added the `RequiresReplace` modifier, but you're still missing the `ImmutableAttributeMode` mode.

2025-01-10 19:42 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
You added the `RequiresReplace` modifier, but you're still missing the `ImmutableAttributeMode` mode.

2025-01-10 19:43 UTC, rlenglet commented on api/schema/tag_to_label_resource.go
> +				"cloud_tags": resource_schema.ListAttribute{
I'd actually rather split this into two attributes, cf. https://github.com/illumio/terraform-provider-illumio-cloudsecure/pull/116#discussion_r1911123532

2025-01-13 22:57 UTC, shireesh-illumio commented on api/schema/tag_to_label_resource.go
> +					MarkdownDescription: "List of tags to map to CloudSecure labels with the specified key. The values of the created labels correspond to the values of the tags. The cloud field for each tag must b
```suggestion
					MarkdownDescription: "List of tags to map to CloudSecure labels with the specified key. The values of the created labels correspond to the values of the tags. The cloud field for each tag must be \"aws\" or \"azure\".",
```

2025-01-15 23:39 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +				},
its editable

2025-01-15 23:39 UTC, shireesh-illumio commented on api/schema/aws_tag_to_label_resource.go
> +				},
its editable

2025-01-15 23:41 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
If it was mutable, then adding the `RequiresReplace` modifier doesn't make sense.

2025-01-15 23:41 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
If it was mutable, then adding the `RequiresReplace` modifier wouldn't make sense.

2025-01-15 23:42 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
OK, I see that you finally removed the `RequiresReplace` modifier. Now it makes sense.

2025-01-15 23:42 UTC, rlenglet commented on api/schema/aws_tag_to_label_resource.go
> +				},
OK, I see that you finally removed the `RequiresReplace` modifier. Now it makes sense.

2025-01-15 23:45 UTC, rlenglet approved these changes
Looks good, thanks!

2025-01-16 00:07 UTC, merged